# Generated by Django 5.2.8 on 2025-12-01 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': '診斷', 'verbose_name_plural': '診斷'},
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'verbose_name': '檢查', 'verbose_name_plural': '檢查'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '圖檔', 'verbose_name_plural': '圖檔'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '病患', 'verbose_name_plural': '病患'},
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='clinical_summary',
            field=models.TextField(blank=True, verbose_name='臨床摘要'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生成時間'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='examination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='diagnosis.examination', verbose_name='檢查'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始數據'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='risk_assessment',
            field=models.JSONField(blank=True, default=dict, verbose_name='風險評估'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='檢查時間'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='檢查ID'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='diagnosis.patient', verbose_name='病患'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL, verbose_name='治療師'),
        ),
        migrations.AlterField(
            model_name='image',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diagnosis.examination', verbose_name='檢查'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slot_type',
            field=models.CharField(choices=[('SLOT_A', 'Slot A: Basic Info/Training Volume'), ('SLOT_B', 'Slot B: Trajectory & Heatmap'), ('SLOT_C', 'Slot C: Comprehensive Analysis')], max_length=10, verbose_name='圖片類型'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上傳時間'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話'),
        ),
    ]
