# Generated by Django 5.2.8 on 2025-12-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_alter_diagnosis_options_alter_examination_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('PROCESSING', '處理中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], default='PENDING', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slot_type',
            field=models.CharField(choices=[('SLOT_A', 'Slot A: 基本資料/訓練量'), ('SLOT_B', 'Slot B: 軌跡與熱圖'), ('SLOT_C', 'Slot C: 綜合分析')], max_length=10, verbose_name='圖片類型'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=10, verbose_name='性別'),
        ),
    ]
