# Generated by Django 5.2.8 on 2025-12-01 02:41

import diagnosis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_alter_examination_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=diagnosis.models.image_upload_path, verbose_name='圖片'),
        ),
    ]
